name: Build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    env:
      IMAGE: ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['frontend', 'backend']
    steps:
      - uses: actions/checkout@v4
      - name: Build with Make
        run: make build
